<?php

//restrict production nodes viewing to privilidges roles
function access_control_node_access($node, $op, $account){

	if(isset($node->type) && ($node->type === 'person' || $node->type === 'business' || $node->type === 'physical_item')){
	//dpm($node);
	//dpm($account);
		if(user_has_role(4) || user_has_role(3) || user_has_role(6) || $node->uid === $account->uid){
			$access = true;
		}else{
			$access = false;
		}
		if(!$access && $op==='view'){
			return NODE_ACCESS_DENY;
		}
	}
}
